2022-02-17T15:13:03|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'plotlines'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 110, in update_display\n    self.plotlines[rate].setVisible(self.settings[\'{}_visible\'.format(rate)])\n', "AttributeError: 'ESRMeasure' object has no attribute 'plotlines'\n"]
2022-02-17T15:13:03|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'plotlines'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 110, in update_display\n    self.plotlines[rate].setVisible(self.settings[\'{}_visible\'.format(rate)])\n', "AttributeError: 'ESRMeasure' object has no attribute 'plotlines'\n"]
2022-02-17T15:13:03|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'plotlines'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 110, in update_display\n    self.plotlines[rate].setVisible(self.settings[\'{}_visible\'.format(rate)])\n', "AttributeError: 'ESRMeasure' object has no attribute 'plotlines'\n"]
2022-02-17T15:13:03|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'plotlines'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 110, in update_display\n    self.plotlines[rate].setVisible(self.settings[\'{}_visible\'.format(rate)])\n', "AttributeError: 'ESRMeasure' object has no attribute 'plotlines'\n"]
2022-02-17T15:13:03|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'plotlines'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 110, in update_display\n    self.plotlines[rate].setVisible(self.settings[\'{}_visible\'.format(rate)])\n', "AttributeError: 'ESRMeasure' object has no attribute 'plotlines'\n"]
2022-02-17T15:13:03|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'plotlines'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 110, in update_display\n    self.plotlines[rate].setVisible(self.settings[\'{}_visible\'.format(rate)])\n', "AttributeError: 'ESRMeasure' object has no attribute 'plotlines'\n"]
2022-02-17T15:13:04|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'plotlines'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 110, in update_display\n    self.plotlines[rate].setVisible(self.settings[\'{}_visible\'.format(rate)])\n', "AttributeError: 'ESRMeasure' object has no attribute 'plotlines'\n"]
2022-02-17T15:13:04|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'plotlines'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 110, in update_display\n    self.plotlines[rate].setVisible(self.settings[\'{}_visible\'.format(rate)])\n', "AttributeError: 'ESRMeasure' object has no attribute 'plotlines'\n"]
2022-02-17T15:13:04|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'plotlines'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 110, in update_display\n    self.plotlines[rate].setVisible(self.settings[\'{}_visible\'.format(rate)])\n', "AttributeError: 'ESRMeasure' object has no attribute 'plotlines'\n"]
2022-02-17T15:13:04|ERROR|ESRMeasure|ESR_measurement Failed to update figure1: 'ESRMeasure' object has no attribute 'plotlines'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\custommeasure2.py", line 110, in update_display\n    self.plotlines[rate].setVisible(self.settings[\'{}_visible\'.format(rate)])\n', "AttributeError: 'ESRMeasure' object has no attribute 'plotlines'\n"]
