2022-10-19T17:04:57|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:57|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:57|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:57|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:58|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:58|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:58|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:58|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:58|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:58|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:58|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:58|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:58|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:59|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:59|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:59|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:59|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:59|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:59|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:59|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:59|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:04:59|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:00|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:01|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:02|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:03|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:04|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:05|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
2022-10-19T17:05:05|ERROR|ThorCamCaptureMeasure|thor_cam_capture Failed to update figure1: resize() missing 1 required positional argument: 'size'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\thorcam_capture.py", line 359, in update_display\n    self.img.resize()\n', "TypeError: resize() missing 1 required positional argument: 'size'\n"]
