2023-06-05T13:26:05|ERROR|ESRImageMeasure|ESRImage Failed to update figure1: 'ESRImageMeasure' object has no attribute 'average_y'. ['Traceback (most recent call last):\n', '  File "C:\\Users\\ZHao\\.conda\\envs\\scopefoundry\\lib\\site-packages\\ScopeFoundry\\measurement.py", line 273, in _on_display_update_timer\n    self.update_display()\n', '  File "C:\\Users\\Public\\quantum_sensing\\quantum_sensing\\fancy_microscope\\ESRMappingMeasure.py", line 199, in update_display\n    self.current_plotline.setData(self.sweep[:self.cutoff], self.average_y[:self.cutoff])\n', "AttributeError: 'ESRImageMeasure' object has no attribute 'average_y'\n"]
