2023-05-30T16:51:44|INFO|ThorCamCaptureMeasure|Camera start_stop False
2023-05-30T16:51:44|INFO|ThorCamCaptureMeasure|measurement Camera interrupt
2023-05-30T16:51:44|INFO|ThorCamTestApp|setting up figures for Camera measurement Camera
2023-05-30T16:52:05|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\Users\Public\quantum_sensing\quantum_sensing\fancy_microscope\thorcam_capture.py", line 453, in execute_move
    moveToPos(device, x, y)
  File "..\movestages.py", line 115, in moveToPos
    moveX(pidevice, [xpos])
  File "..\movestages.py", line 128, in moveX
    pidevice.MOV(axis, target)
  File "..\pipython\pidevice\common\gcsbasecommands.py", line 5327, in MOV
    self._msgs.send(cmdstr)
  File "..\pipython\pidevice\gcsmessages.py", line 135, in send
    self._checkerror(senderr=not self.embederr)
  File "..\pipython\pidevice\gcsmessages.py", line 339, in _checkerror
    raise exc  # Raising NoneType while only classes or instances are allowed pylint: disable=E0702
pipython.pidevice.gcserror.GCSError: Illegal axis or channel (23)

2023-05-30T16:53:41|INFO|ThorCamTestApp|on_close
2023-05-30T16:53:41|INFO|ThorCamTestApp|disconnecting thor_cam
